### ISSUE TITLE
Adding new examples and algorithms for TQ

### ISSUE THREAD

**Issue by GenericP3rson** [mit-han-lab/torchquantum#264]
To enrich torchquantum's support of various algorithms, we need your help on implementing more quantum algorithms and examples in TQ! You may choose any quantum algorithm you like to implement such as QSVT or generative quantum models. Once complete, add a Python file and notebook to `examples` and (if you see fit) an algorithm to `torchquantum/algorithms`!

Please don't hesitate to let us know for any questions!

**Comment by anonymousr007** [comment]
Hi @GenericP3rson, Nice to meet you. 

I am Rishabh Singh, and I have been learning about quantum computing since 2020. 

- Experience - Qiskit, Pennylane and Cirq.
- Participation - Quantum Hackathons, Qiskit Summer School and IBM Quantum Challenges.
- Open Source Contribution - Cirq, Pennylane, Scikit-Learn.
- I am interested in this issue and want to contribute.

Best Regards 
Rishabh Singh
[LinkedIn](https://www.linkedin.com/in/anonymousr007/) | [GitHub](https://github.com/anonymousr007)

**Comment by GenericP3rson** [comment]
Hello, I've just assigned you the task! What are you planning to implement?

**Comment by Gopal-Dahale** [comment]
@GenericP3rson, updated with QCBM's implementation and its example.

**Comment by GubioGL** [comment]
Hi, I would like to tackle this issue as part of the UnitaryHack
