### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by wcqc** [mit-han-lab/torchquantum#51]
import torch
import torchquantum as tq
import torchquantum.functional as tqf

from qiskit import QuantumCircuit
import qiskit.quantum_info as qi

qc_AB = QuantumCircuit(2)
qc_AB.cx(0, 1)
qc_AB.cy(0, 1)
qc_AB.cz(1, 0)
qc_AB.h(1)
print(qi.Statevector(qc_AB).data)

x = tq.QuantumDevice(n_wires=2)
tqf.cx(x, wires=[0, 1])
tqf.cy(x, wires=[0, 1])
tqf.cz(x, wires=[1, 0])
tqf.h(x, wires=1)
print(x.get_states_1d())

This results in two different state vectors:

[0.70710678+0.j 0.        +0.j 0.70710678+0.j 0.        +0.j]
tensor([[0.7071+0.j, 0.7071+0.j, 0.0000+0.j, 0.0000+0.j]])

**Comment by wcqc** [comment]
Maybe this is due to the qubit ordering in qiskit not a TQ bug?

**Comment by Hanrui-Wang** [comment]
Hi wcqc,

Thank you for your feedback! Yes, the reason is the big endian little endian difference between tq and qiskit. You may use the function switch_little_big_endian_state in tq.utils to switch between two. 

https://github.com/mit-han-lab/torchquantum/blob/2ebb60665bd96a7f27c1fa05d62f16e627499438/torchquantum/utils.py#L116 
 
Thanks!
Hanrui

**Comment by Hanrui-Wang** [comment]
I'm going to close this issue for now. Feel free to reopen for any more questions!
